name: Build runtimes

on:
  push:
    branches: [ "main" ]
    paths:
      - 'runtimes/**'

jobs:
  build-python-3-13:
    name: Build Python 3.13 runtime
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create output directories
        run: mkdir -p dist artifacts
        working-directory: runtimes

      - name: Build generate-ext4 helper image
        run: docker build --platform linux/amd64 -t generate-ext4 .
        working-directory: runtimes

      - name: Build Python 3.13 runtime
        run: |
          chmod +x ./generate-rootfs.sh
          ./generate-rootfs.sh lambda-at-home-runtime-python:3.13 ./runtimes/python/3.13/Dockerfile
        working-directory: runtimes

      - name: Upload ext4 artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-3.13-runtime
          path: runtimes/artifacts/lambda-at-home-runtime-python-3.13.ext4

  build-python-3-14:
    runs-on: ubuntu-latest
    name: Build Python 3.14 runtime
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create output directories
        run: mkdir -p dist artifacts
        working-directory: runtimes

      - name: Build generate-ext4 helper image
        run: docker build --platform linux/amd64 -t generate-ext4 .
        working-directory: runtimes

      - name: Build Python 3.14 runtime
        run: |
          chmod +x ./generate-rootfs.sh
          ./generate-rootfs.sh lambda-at-home-runtime-python:3.14 ./runtimes/python/3.14/Dockerfile
        working-directory: runtimes

      - name: Upload ext4 artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-3.14-runtime
          path: runtimes/artifacts/lambda-at-home-runtime-python-3.14.ext4

  create-image:
    name: Create image
    runs-on: ubuntu-latest
    needs: [build-python-3-13, build-python-3-14]
    steps:
      - name: Download Python 3.13 runtime artifact
        uses: actions/download-artifact@v4
        with:
          name: python-3.13-runtime
          path: artifacts

      - name: Download Python 3.14 runtime artifact
        uses: actions/download-artifact@v4
        with:
          name: python-3.14-runtime
          path: artifacts

      - name: List artifacts
        run: |
          echo "Artifacts:"
          ls artifacts/
