name: Build and deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build-and-deploy.yml'
      - 'runtimes/**'
      - '**/*.go'

jobs:
  build-go:
    name: Build Go project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create output directories
      run: mkdir -p artifacts

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26'

    - name: Build
      run: go build -o artifacts/lambda-at-home -v ./...

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-binary
        path: artifacts/lambda-at-home

  build-runtimes:
    name: Build ${{ matrix.name }} runtime
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Python 3.13
            image: lambda-at-home-runtime-python:3.13
            dockerfile: ./runtimes/python/3.13/Dockerfile
            artifact: python-3.13-runtime
          - name: Python 3.14
            image: lambda-at-home-runtime-python:3.14
            dockerfile: ./runtimes/python/3.14/Dockerfile
            artifact: python-3.14-runtime
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create output directories
        run: mkdir -p dist artifacts
        working-directory: runtimes

      - name: Build generate-ext4 helper image
        run: docker build --platform linux/amd64 -t generate-ext4 .
        working-directory: runtimes

      - name: Build runtime
        run: |
          chmod +x ./generate-rootfs.sh
          ./generate-rootfs.sh ${{ matrix.image }} ${{ matrix.dockerfile }}
        working-directory: runtimes

      - name: Upload ext4 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: runtimes/artifacts/${{ matrix.artifact }}*.ext4

  create-image:
    name: Create image
    runs-on: ubuntu-latest
    needs: [build-go, build-runtimes]
    steps:
      - name: Download runtime artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: |
          echo "Artifacts:"
          ls artifacts/
